### ISSUE TITLE
new --advisory review to close the --issue review of num-traits 0.2.6

### ISSUE THREAD

**Issue by bestia-dev** [HeroicKatora/crev-proofs#1]
Hello. 
I am learning to use `cargo-crev`. I believe it is a fantastic idea and needs to be promoted.
In my project there is dependency to `num-traits 0.2.11`.
When I `crev verify` I see 2 `issues` for it. One in red and one in yellow color.
```
status issues flgs crate                version         latest_t 
pass    1   1 CB__ num-traits           0.2.11          =
```
`cargo crev repo query issue num-traits` returns your review with one `issue` for version 0.2.6.
I went to github and  this issue is closed/solved in later versions.
I asked the author of `cargo-crev` how to close this issue in the crev review system.
He replied:
> Advisories with the same id, mark issues as solved. So in this case create a review (even with everything set to none) for 0.2.6 with an advisory (--advisory).

I expect that this will show the version 0.2.6 as problematic (with advisory), but future versions to not have this issue any more.
Can you please do a new review with --advisory for the same crate version 0.2.6?  

Thank you, Luciano

**Comment by 197g** [comment]
I did a re-review of `0.2.11`, the latest version, and then did an advisory review of version `0.2.9` where the issue was fixed. It seems to have worked, the report for `image` which also uses this crate and version comes back with no issues here.
